[build-system]
requires = ["setuptools>=61", "setuptools-scm[toml]>=8", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "lerobot_robot_seeed_b601_rt"
dynamic = ["version"]
description = "Seeed reBot Arm B601 motorbridge and RT follower integration with LeRobot"
readme = "README.md"
authors = [
  { name = "dongyaolin" },
]
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.10"
classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent",
]
dependencies = [
  "lerobot>=0.4",
  "motorbridge>=0.4.4",
  "python-can>=4.2.0,<5.0.0",
  "rebotarm-control-rt",
]

[project.optional-dependencies]
taccap = [
  "taccap-gripper>=0.1.5",
]
serial-gripper = ["xgripper"]
all = [
  "taccap-gripper>=0.1.5",
  "xgripper",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["lerobot_robot_seeed_b601_rt*"]
exclude = ["*.egg-info"]

[tool.setuptools_scm]
tag_regex = "^v(?P<version>\\d+\\.\\d+\\.\\d+)$"
fallback_version = "0.0.0"
